version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: altenShop
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    

#volumes:
  #postgres-user-data:

